import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The documentation-standards content is vendored from the .github submodule
// (symlinked), so we can't drop a _category_.json inside it to set the
// sidebar label — it's wired up explicitly here instead (same pattern as
// developSidebars.ts for the per-component vendored docs).
const sidebars: SidebarsConfig = {
  communitySidebar: [
    'support',
    'team',
    'funding',
    'licensing',
    'code-of-conduct',
    'contribution',
    'citing-us',
    {
      type: 'category',
      label: 'Documentation Standards',
      link: {type: 'doc', id: 'documentation-standards/documentation-standards'},
      items: [{type: 'autogenerated', dirName: '07-documentation-standards'}],
    },
  ],
};

export default sidebars;
