import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Prelude and Quickstart are marked `unlisted` (hidden for now, still
  // reachable by direct link) so they're left out here rather than
  // autogenerated. The 3 deployment guide pages are hoisted to the sidebar
  // root instead of nested under a "Deployment Guide" category/dropdown;
  // their own overview page (deployment/index) is unlisted too, so it's
  // left out here as well.
  deploySidebar: [
    "index",
    "deployment/authorization",
    "deployment/data-management-storage",
    "deployment/search-portal",
  ],
};

export default sidebars;
