import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Prelude and Quickstart are marked `unlisted` (hidden for now, still
  // reachable by direct link) so they're left out here rather than
  // autogenerated. The deployment docs are organized into service categories
  // so users can open individual pages for each deployable service.
  deploySidebar: [
    "index",
    {
      type: "category",
      label: "Authorization",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["deployment/keycloak"],
    },
    {
      type: "category",
      label: "File Transfer",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["deployment/song", "deployment/score"],
    },
    {
      type: "category",
      label: "Tabular Data Submission",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["deployment/lectern", "deployment/lyric"],
    },
    {
      type: "category",
      label: "Search Portal",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        "deployment/search-engine",
        "deployment/maestro",
        "deployment/arranger",
        "deployment/stage",
        "deployment/arranger-mcp-server",
      ],
    },
  ],
};

export default sidebars;
