import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Each component's docs are vendored from its own submodule (symlinked), so we
// can't drop a _category_.json inside them to set the sidebar label. Instead
// each is wired up explicitly here, paired as "Overture name (functional
// name)" per the site map convention.
const components: Array<{ dirName: string; id: string; label: string }> = [
  {
    dirName: "01-Lectern",
    id: "Lectern",
    label: "Lectern (Dictionary Management)",
  },
  { dirName: "02-Lyric", id: "Lyric", label: "Lyric (Data Management)" },
  { dirName: "03-Song", id: "Song", label: "Song (File Management)" },
  { dirName: "04-Score", id: "Score", label: "Score (File Transfer)" },
  { dirName: "05-Maestro", id: "Maestro", label: "Maestro (Indexing)" },
  { dirName: "06-Arranger", id: "Arranger", label: "Arranger (Search)" },
  { dirName: "07-Stage", id: "Stage", label: "Stage (Portal UI)" },
];

const sidebars: SidebarsConfig = {
  developSidebar: [
    "index",
    ...components.map(({ dirName, id, label }) => ({
      type: "category" as const,
      // Scoped by className so the "Overture name (functional name)" pairing
      // (long enough to wrap on some of these) can get its own sidebar
      // styling in custom.css without affecting other sidebars.
      className: "sidebar-component-item",
      label,
      link: { type: "doc" as const, id: `${id}/overview` },
      items: [{ type: "autogenerated" as const, dirName }],
    })),
    "api-reference",
    "contributing",
  ],
};

export default sidebars;
