import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  useSidebar: [
    "index",

    {
      type: "category",
      label: "File Transfer",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        {
          type: "category",
          label: "Song",
          link: {
            type: "doc",
            id: "Song/overview",
          },
          items: [{ type: "autogenerated", dirName: "03-Song" }],
        },
        {
          type: "category",
          label: "Score",
          link: {
            type: "doc",
            id: "Score/overview",
          },
          items: [{ type: "autogenerated", dirName: "04-Score" }],
        },
      ],
    },

    {
      type: "category",
      label: "Tabular Data Submission",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        {
          type: "category",
          label: "Lectern",
          link: {
            type: "doc",
            id: "Lectern/overview",
          },
          items: [{ type: "autogenerated", dirName: "01-Lectern" }],
        },
        {
          type: "category",
          label: "Lyric",
          link: {
            type: "doc",
            id: "Lyric/overview",
          },
          items: [{ type: "autogenerated", dirName: "02-Lyric" }],
        },
        {
          type: "category",
          label: "Maestro",
          link: {
            type: "doc",
            id: "Maestro/overview",
          },
          items: [{ type: "autogenerated", dirName: "05-Maestro" }],
        },
      ],
    },

    {
      type: "category",
      label: "Search Portal",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        {
          type: "category",
          label: "Arranger",
          link: {
            type: "doc",
            id: "Arranger/overview",
          },
          items: [{ type: "autogenerated", dirName: "06-Arranger" }],
        },
        {
          type: "category",
          label: "Stage",
          link: {
            type: "doc",
            id: "Stage/overview",
          },
          items: [{ type: "autogenerated", dirName: "07-Stage" }],
        },
      ],
    },
  ],
};

export default sidebars;
