import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The Use journey serves three distinct audiences. Each group below is a
// non-collapsible "section heading" (collapsible: false, no link, styled as
// a plain label in custom.css via the sidebar-section-heading className)
// rather than a dropdown category, so the audience split is visible at a
// glance instead of hidden behind a toggle.
const sidebars: SidebarsConfig = {
  useSidebar: [
    "index",
    {
      type: "category",
      label: "Data Consumers",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["ai-assisted-data-discovery", "cli-downloads"],
    },
    {
      type: "category",
      label: "Data Submitters",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["cli-submissions"],
    },
    {
      type: "category",
      label: "Platform Administrators",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        {
          type: "category",
          label: "Build a Search Portal",
          link: { type: "doc", id: "workshop/prerequisites" },
          items: [{ type: "autogenerated", dirName: "workshop" }],
        },
        {
          type: "category",
          label: "Configuration Guides",
          items: [{ type: "autogenerated", dirName: "administration" }],
        },
      ],
    },
  ],
};

export default sidebars;
