import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The Use journey serves three distinct audiences. Each group below is a
// non-collapsible "section heading" (collapsible: false, no link, styled as
// a plain label in custom.css via the sidebar-section-heading className)
// rather than a dropdown category, so the audience split is visible at a
// glance instead of hidden behind a toggle.
const sidebars: SidebarsConfig = {
  useSidebar: [
    "index",
    {
      type: "category",
      label: "Data Consumers",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["conversational-data-discovery", "cli-downloads"],
    },
    {
      type: "category",
      label: "Data Submitters",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["cli-submissions"],
    },
    {
      type: "category",
      label: "Platform Administrators",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        "administration/building-dictionaries",
        "administration/building-song-schemas",
        "administration/index-mappings",
        "administration/customizing-the-data-portal",
        // A tutorial with its own multi-step sequence stays a normal
        // collapsible category, nested under Platform Administrators since
        // it's an end-to-end walkthrough of the tasks above.
        {
          type: "category",
          label: "Build a Search Portal",
          link: { type: "doc", id: "workshop/prerequisites" },
          items: [{ type: "autogenerated", dirName: "03-workshop" }],
        },
      ],
    },
  ],
};

export default sidebars;
