import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The Use journey serves three distinct audiences. Each group below is a
// non-collapsible "section heading" (collapsible: false, no link, styled as
// a plain label in custom.css via the sidebar-section-heading className)
// rather than a dropdown category, so the audience split is visible at a
// glance instead of hidden behind a toggle.
const sidebars: SidebarsConfig = {
  useSidebar: [
    "index",
    {
      type: "category",
      label: "Data Consumers",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        {
          type: "category",
          label: "AI-Assisted Data Discovery",
          link: { type: "doc", id: "ai-assisted-data-discovery/index" },
          items: [
            "ai-assisted-data-discovery/testing-environment",
            "ai-assisted-data-discovery/connect-a-host",
            "ai-assisted-data-discovery/configuration-templates",
            "ai-assisted-data-discovery/use-cases",
            "ai-assisted-data-discovery/deploy-your-own-mcp-server",
          ],
        },
        "cli-downloads",
      ],
    },
    {
      type: "category",
      label: "Data Submitters",
      collapsible: false,
      className: "sidebar-section-heading",
      items: ["cli-submissions"],
    },
    {
      type: "category",
      label: "Platform Administrators",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        {
          type: "category",
          label: "Build a Foundational Search Portal",
          link: { type: "doc", id: "workshop/prerequisites" },
          items: [{ type: "autogenerated", dirName: "workshop" }],
        },
        {
          type: "category",
          label: "Configuration Guides",
          items: [{ type: "autogenerated", dirName: "administration" }],
        },
        {
          type: "category",
          label: "Generators & Playgrounds",
          link: { type: "doc", id: "config-generators-and-playgrounds/index" },
          items: [
            "config-generators-and-playgrounds/config-generator",
            "config-generators-and-playgrounds/dictionary-playground",
            "config-generators-and-playgrounds/song-schema-playground",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
